begin;

-- 독립 주제 목록을 만들고 공통 문항과 교육별 문항 복사본에 그룹 메타데이터를 추가합니다.
-- 기존 문항 내용·유형, 설문 응답, 문항별 답변은 삭제하거나 변경하지 않습니다.
alter table public.survey_question_templates
  add column if not exists group_name text,
  add column if not exists group_order integer;

alter table public.course_survey_questions
  add column if not exists group_name text,
  add column if not exists group_order integer;

-- 문항이 없는 주제도 저장할 수 있는 공통 주제 테이블입니다.
create table if not exists public.survey_question_groups (
  id bigint generated by default as identity primary key,
  name text not null check (btrim(name) <> ''),
  display_order integer not null default 1,
  created_at timestamptz not null default now()
);

-- 대소문자와 앞뒤 공백만 다른 동일 주제의 중복 저장도 차단합니다.
create unique index if not exists survey_question_groups_name_ci_key
on public.survey_question_groups (lower(btrim(name)));

-- 기존 문항은 모두 '기본 문항' 그룹으로 안전하게 계속 표시합니다.
-- 이미 그룹 값이 있는 행은 그대로 보존합니다.
update public.survey_question_templates
set group_name = '기본 문항'
where group_name is null or btrim(group_name) = '';

update public.course_survey_questions
set group_name = '기본 문항'
where group_name is null or btrim(group_name) = '';

update public.survey_question_templates
set group_order = 1
where group_order is null;

update public.course_survey_questions
set group_order = 1
where group_order is null;

-- 이후 생성되는 행도 그룹 없이 저장되지 않도록 기본값과 제약을 설정합니다.
alter table public.survey_question_templates
  alter column group_name set default '기본 문항',
  alter column group_name set not null,
  alter column group_order set default 1,
  alter column group_order set not null;

alter table public.course_survey_questions
  alter column group_name set default '기본 문항',
  alter column group_name set not null,
  alter column group_order set default 1,
  alter column group_order set not null;

comment on column public.survey_question_templates.group_name is '공통 만족도 문항의 그룹(주제)명';
comment on column public.survey_question_templates.group_order is '공통 만족도 문항 그룹 표시 순서';
comment on column public.course_survey_questions.group_name is '교육 생성 시 복사된 만족도 문항의 그룹(주제)명';
comment on column public.course_survey_questions.group_order is '교육 생성 시 복사된 만족도 문항 그룹 표시 순서';

-- 현재 문항에서 사용 중인 주제를 독립 주제 목록으로 옮깁니다.
-- 문항 행 자체는 수정하거나 이동하지 않습니다.
insert into public.survey_question_groups (name, display_order)
select source.name, source.display_order
from (
  select min(btrim(group_name)) as name, min(group_order) as display_order
  from public.survey_question_templates
  group by lower(btrim(group_name))
) as source
where not exists (
  select 1
  from public.survey_question_groups as existing
  where lower(btrim(existing.name)) = lower(btrim(source.name))
)
order by source.display_order
on conflict do nothing;

-- 기본 주제 3개는 문항이 없어도 주제 카드로 유지합니다.
insert into public.survey_question_groups (name, display_order)
select preset.name,
       coalesce((select max(display_order) from public.survey_question_groups), 0) + preset.preset_order
from (values
  ('교육 내용 만족도', 1),
  ('강사 및 운영 만족도', 2),
  ('전반적 만족도', 3)
) as preset(name, preset_order)
where not exists (
  select 1
  from public.survey_question_groups as existing
  where lower(btrim(existing.name)) = lower(btrim(preset.name))
)
on conflict do nothing;

-- 만족도 문항 설정 화면은 로그인한 관리자만 주제를 관리합니다.
alter table public.survey_question_groups enable row level security;

drop policy if exists "survey_question_groups_authenticated_select" on public.survey_question_groups;
create policy "survey_question_groups_authenticated_select"
on public.survey_question_groups
for select
to authenticated
using (true);

drop policy if exists "survey_question_groups_authenticated_insert" on public.survey_question_groups;
create policy "survey_question_groups_authenticated_insert"
on public.survey_question_groups
for insert
to authenticated
with check (true);

drop policy if exists "survey_question_groups_authenticated_update" on public.survey_question_groups;
create policy "survey_question_groups_authenticated_update"
on public.survey_question_groups
for update
to authenticated
using (true)
with check (true);

grant usage on schema public to authenticated;
grant select, insert, update on table public.survey_question_groups to authenticated;
grant usage, select on sequence public.survey_question_groups_id_seq to authenticated;

commit;
